export const DECORATOR_KEYS = {
    PRIMARY_KEY: Symbol.for("PRIMARY_KEY"),
    MANDATORY_KEY: "MANDATORY_KEY",
    IGNORE_MANDATORY_KEY: "IGNORE_MANDATORY_KEY",
    IGNORE_KEY: "IGNORED_KEY",
    NOT_IGNORE_KEY: "NOT_IGNORED_KEY"
}